### ISSUE TITLE
AMR stopped working? Website also down

### ISSUE THREAD

**Issue by monkey8113** [AllMangasReader-dev/AMR#150]
Suddenly a moment ago, AMR stopped working, ive no idea what caused this. I was reading nicely then when i go to next chapter AMR just stopped working altogether, And the website is down when im trying to check for any new update.
Could the website affect the plugin in any way?

**Comment by monkey8113** [comment]
p/s after awhile the website came back and the plugin works again!

Why is the plugins dependent on the website? Im curious

**Comment by braiam** [comment]
Because the chaotic nature of the mirrors we support and current context, each time we updated a single site all users would download a new version, which represent ~6GB of downstream from the server. The current method allows us to, while not having to release a new version, add, remove or update the list of supported mirrors.

I'm planning on relaxing the dependency on our servers, but that will take time.
